# -*- coding: utf-8 -*-
"""1975660_ADS1_B_2023_lista3_programacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13_mEA2Fo4NgcxthIt3bu5Zy6JkSUI97o

1. Crie um algoritmo que mostre todos os números inteiros de 0 a 10.
"""

i = 0

while i < 11:
    print(i)
    i+=1

"""2. Crie um algoritmo que peça um valor limite e mostre todos os números inteiros entre 0 até o número digitado."""

limite = int(input('Escolha um valor limite = '))
i = 0
while i < limite+1:
    print(i)
    i += 1

"""3. Crie um algoritmo que mostre apenas os números pares de 0 a 100."""

i = 0
while i < 101:
    if i%2 == 0:
        print(i)
    i += 1

"""4. Crie um algoritmo que peça um valor e mostre sua tabuada de 1 a 10."""

o = int(input('Escolha um valor e sua tabuada será mostrada = '))
i = 0

print('A tabuada desse valor é de:')
while i < 11:    
    print(f'{o} X {i} = {o*i}')
    i += 1

"""5. Faça um algoritmo em Python que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5! = 5.4.3.2.1=120. A saída deve ser conforme o exemplo abaixo:"""

fatorial = 1
o = int(input('Informe o fatorial de: '))
print(f'Fatorial de {o}:')
print(f'{o}! =', end='')

while o > 0:
    fatorial *= o
    if o != 1:
        print(f'{o}', end='')
    else:
        print(f'{o}, =, {fatorial}', end='')

"""6. Um mercadinho de bairro expandiu seus caixas e funcionários, agora eles precisam de um software que implemente uma caixa registradora simples. O programa deverá receber um número desconhecido de valores referentes aos preços das mercadorias. Um valor zero deve ser informado pelo operador para indicar o final da compra. O programa deve então mostrar o total da compra e perguntar o valor em dinheiro que o cliente forneceu, para então calcular e mostrar o valor do troco. Após esta operação, o programa deverá voltar ao ponto inicial, para registrar a próxima compra. A saída deve ser conforme o exemplo abaixo:"""

('Bem vindo ao Mercadinho Bigbo')
i = 1
cont = 1
total = 0

while i != 0:
    i = float(input(f'Produto {cont}: R$ '))
    total += i
    cont += 1

print('-'*30)
print(f'Total: R${total}')
print('-'*30)

pagamento = float(input('Qual será sua quantia de pagamento: '))
print(f'Troco: R$ {pagamento - total}')

"""7. Ler uma lista de 5 números inteiros e mostre cada número juntamente com a sua posição na lista."""

lista = [10,11,22,33,44]

i= 0 
while i < len(lista):
    print(f'{i} - {lista[i]}') 
    i +=1

"""8. Crie um algoritmo que leia 20 números inteiros e os guarde em uma lista. Além de guardar todos em uma única lista, separe os números pares em uma lista “PAR” e os ímpares em uma lista “IMPAR”. No final mostre as três listas e seus valores."""

import random
lista = []
par = []
impar = []
i = 0

while i < 20:
    a = random.randint(0,100)
    lista.append(a)

    if a%2 == 0:
        par.append(a)
    else:
        impar.append(a)
    
    i +=1

print(f'Lista total {lista}\n')
print(f'Lista de pares {par}\n')
print(f'Lista de ímpares {impar}')

"""9. Crie um algoritmo que leia 4 notas de 10 aluno, calcule e guarde em uma lista a média de cada aluno. No final, mostre quantos alunos tiveram a média maior ou igual a 7. É obrigatório uma lista com todas as médias e no final gerar um único valor inteiro do número de alunos com média maior ou igual a 7."""

medias = []
i = 0
total = 0

while i < 10:
    n1 = float(input('Qual foi sua nota N1 = '))
    n2 = float(input('Qual foi sua nota N2 = '))
    n3 = float(input('Qual foi sua nota N3 = '))
    n4 = float(input('Qual foi sua nota N4 = '))

    total = (n1 + n2 + n3 + n4)/4
    medias.append(total)
    i += 1

i = 0
x = 0
while i < len(medias):
    if medias[i] >= 7:
        x += 1
    i += 1

print(f'Alunos e suas médias {medias}')
print(f'Médias acima de 7 = {x}')

"""10. Crie um algoritmo que leia 10 números, guarde-os em uma lista “ORDEM”. Depois gere uma segunda lista “REVERSA” que deve conter os elementos em ordem inversa a original."""

import random
lista = []
i = 0

while i < 10:
    n = random.randint(0,100)
    lista.append(n)

    i += 1

print(lista)

reverso = []
i = 9
while i > -1:
    reverso.append(lista[i])
    i -= 1

print(reverso)

"""11. Faça um algoritmo que leia duas listas com 10 elementos cada. Gere uma terceira lista de 20 elementos, cujos valores deverão ser compostos pelos elementos intercalados das duas outras listas."""

import random
lista1 = []
lista2 = []

i = 0

while i < 10:
    a = random.randint(0,100)
    b = random.randint(0,100)

    lista1.append(a)
    lista2.append(b)

    i += 1

print(lista1)
print(lista2)

lista3 = []
i = 0
while i < 10:
    lista3.append(lista1[i])
    lista3.append(lista2[i])
    i += 1

print(lista3)

"""12. Você foi contratado por uma empresa de pesquisas e análise de dados, para apoiar um projeto. Nesse projeto você vai implementar uma enquete sobre o uso de Sistemas Operacionais para servidores. Como abaixo:

O seu papel como desenvolvedor da enquete será dividido em alguns objetivos:
1. Desenvolver o questionário conforme a pergunta e as opções apresentados acima. Não deverão aceitar valores além do válidos para o programa, de 0 a 6. A leitura de enquete se encerra quando a opção digitada por 0.
2. Os valores referentes a cada opção da enquete devem armazenados em uma lista.
3. Após os dados terem sido completamente informados, o programa deverá calcular a percentual de cada um dos concorrentes e informar o vencedor da enquete. O formato da saída foi dado pela empresa, e é o seguinte:
"""

win = []
unix = []
lin = []
net = []
mac = []
outro = []
n = 0
i = 0
total = 0 
maior = 0 
print('Qual o melhor sistema operacional para uso em servidores? ')

while True:
    n = input('''
----------------------------------
As possíveis respostas são:
1- Windows Server
2- Unix
3- Linux
4- Netware
5- Mac OS
6- Outro
0- sair
-----------------------------------
''' )
    if n == '1':
        win.append(n)
        if len(win) > maior:
            maior = len(win)
    elif n == '2':
        unix.append(n)
        if len(unix) > maior:
            maior = len(unix)
    elif n == '3':
        lin.append(n)
        if len(lin) > maior:
            maior = len(lin)
    elif n == '4':
        net.append(n)
        if len(net) > maior:
            maior = len(net)
    elif n == '5':
        mac.append(n)
        if len(mac) > maior:
            maior = len(mac)
    elif n == '6':
        outro.append(n)
        if len(outro) > maior:
            maior = len(outro)
    elif n == '0':
        break
    i += 1

total = len(win) + len(unix) + len(lin) + len(net) + len(mac) + len(outro)



print(f'''
Sistema Operacinal           Votos               %
------------------          -------             ----
Windows Server              {len(win)}\t\t\t{((len(win) * 100)/total):.2f}
Unix                        {len(unix)}\t\t\t{((len(unix) * 100)/total):.2f}
Linux                       {len(lin)}\t\t\t{((len(lin) * 100)/total):.2f} 
Netware                     {len(net)}\t\t\t{((len(net) * 100)/total):.2f}
Mac OS                      {len(mac)}\t\t\t{((len(mac) * 100)/total):.2f}
Outro                       {len(outro)}\t\t\t{((len(outro) * 100)/total):.2f}
------------------          --------            ------
Total                       {total}
''')

print(f'O Sistema Operacional mais votador foi o {maior}, com {total} votos, cirrespondendo a {((maior*100)/total):.2f} % dos votos.')