# -*- coding: utf-8 -*-
"""1975660_ADS1_B_2023_lista1_programacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZGiOUX_WRHu_IHCM_iBZC5jxnXlWHTvL

Execício 01
"""

# Questão 01
x = int(input(f'Escolha uma medida em metros = '))

cent = x * 100

print(f'{x} metros será igual a {cent} centímetros.')

"""Execício 02"""

# Questão 02
x = float(input(f'Qual é remuneração por hora = '))
y = float(input(f'Quantas horas você trabalha por mês = '))

salario = x * y

print(f'Se você recebe {x} por hora, então seu salário será de {salario:.2f} R$ ')

"""Execício 03"""

# Questão 03
f = float(input('Qual é a temperatura ai nos USA? '))

c = 5 * ((f-32)/9)

print(f'Fazendo a conversão Fahrenheit para Celsius será igual {c} Cº')

"""Execício 04"""

# Questão 04
peso = float(input('Qual o seu peso = '))
altura = float(input('Qual a sua altura = '))

imc = peso / (altura * altura)

print(imc)

"""Execício 05"""

# Questão 05
p = float(input('Quantos quilos de peixe trouxe? '))

excesso = p - 30
multa = excesso * 3

print(f'Senhor Zé você pescou {p} quilos de peixe.')
print(f'Sendo o excedente {excesso} quilos, esses serão passíveis de multa por quilo a mais.')
print(f'Em seu caso a multa será de {multa:.2f} reais. ')

"""Execício 06"""

# Questão 06
x = float(input(f'Qual é remuneração por hora = '))
y = float(input(f'Quantas horas você trabalha por mês = '))

salario = x * y
ir = salario * 0.11
inss = (salario - ir) * 0.08
sl = salario - (ir + inss)

print(f'Se você recebe {x} por hora, então o seu salário burto será de {salario:.2f} R$ ')
print(f'O valor do Imposto de Renda é de = {ir}')
print(f'O valor do Imposto do INSS será de = {inss} ')
print(f'Se você recebe {salario} R$ por mês, o seu total líquido após desconto de impostos sobrará {sl}')

"""Execício 07"""

# Questão 07
a = float(input('Qual é a comprimento do local? '))
b = float(input('Qual é a largura do local? '))

import math
area = a * b
tinta = math.ceil(area/3)
pote = math.ceil(tinta/18)
valor = pote*80
compras = valor/80 

print(f'O terreno terá {area} m² e necessitará {tinta} litros de tinta, sendo necessário {pote} potes, custando a faculdade {valor:.2f} R$')