# -*- coding: utf-8 -*-
"""1975660_ADS_1_B_2023_lista2_programacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zXDO0h4g8UC0X6IvSRKAzgh7LXeRFLMw

Exercício 1
"""

n = int(input('Escolha uma valor em minutos = '))

seg = n * 60

print(f'{n} convertido em segundos é igual a {seg}')

"""Exercício 2"""

n = int(input('Escolha uma valor em segundos = '))

inteiro = n // 60
resto = n %60

print(f'{n} convertido em minutos é igual a {inteiro} : {resto}')

"""Exercício 3"""

n = int(input('Escreva um valor inteiro = '))
f = float(input('Escreva um valor float = '))
a = input('Escreva uma string, palavra ou numero sem valor para calcúlo = ')

print(n)
print(f)
print(a)

"""Exercício 4"""

a = int(input('Escolha um valor = '))
b = int(input('Escolha um valor = '))
c = int(input('Escolha um valor = '))

soma = a + b + c
sub = a - b - c
div = a / b / c
mult = a * b * c

print(f'O resultado da soma {soma}')
print(f'O resultado da sub {sub}')
print(f'O resultado da div {div}')
print(f'O resultado da mult {mult}')

"""Exercício 5"""

a = float(input('Escolha valor com decimais = '))
b = float(input('Escolha valor com decimais = '))

div1 = a / b
div2 = b / a
mult = a * b
resto1 = a % b
resto2 = b % a
inteira1 = a // b
inteira2 = b // a

print(f'O resultado da divisão 1 é igual {div1}')
print(f'O resultado da divisão 2 é igual {div2}')
print(f'O resultado da multiplicação {mult}')
print(f'O resultado do resto 1 é igual {resto1}')
print(f'O resultado do resto 1 é igual {resto2}')
print(f'O resultado da divisão inteira 1 é igual a {inteira1}')
print(f'O resultado da divisão inteira 2 é igual a {inteira2}')

"""Exercício 6"""

n = int(input('Escolha um valor inteiro = '))

if n >= 90:
    print('Dezena é igual 9')
elif n >= 80:
    print('Dezena é igual 8')
elif n >= 70:
    print('Dezena é igual 7')
elif n >= 60:
    print('Dezena é igual 6')
elif n >= 50:
    print('Dezena é igual 5')
elif n >= 40:
    print('Dezena é igual 4')
elif n >= 30:
    print('Dezena é igual 3')
elif n >= 20:
    print('Dezena é igual 2')
elif n >= 10:
    print('Dezena é igual 1') 
elif n >= 0:
    print('Dezena é igual 0')

"""Exercício 6a"""

n = int(input('Escolha um valor inteiro = '))

resul = n//10

print(f'A dezena é igual a {resul}')

"""Exercício 7"""

n = int(input('Escolha um valor até 9999 = '))

if n <= 9999 and n >= 1000:
    print('Número é igual a milhar')
elif n >= 100:
    print ('Número é igual a centena') 
elif n >= 10:
    print ('Número é igual a dezena')
elif n >= 0:
    print ('Número é igual a unidade')

"""Exercício 7a"""

n = int(input('Escolha um valor até 9999 = '))

m = n//1000
c = n % 1000
cen = c // 100
d = c % 100
dez = d //10
u = d % 10


print(f'Casa dos milhar = {m}')
print(f'Casa dos centena = {cen}')
print(f'Casa dos dezena = {dez}')
print(f'Casa dos unidade = {u}')

"""Exercício 8"""

a = int(input('Escolha um número = '))
b = int(input('Escolha um número = '))
c = int(input('Escolha um número = '))
d = int(input('Escolha um número = '))
e = int(input('Escolha um número = '))

media = (a + b + c + d + e)/5

print(f'A média da soma dos 5 valores é igual {media}')

"""Exercício 9"""

n = int(input('Escolha um valor em metros = '))

cent = n * 100
kilo = n / 1000

print(f'O valor d {n} metros em centímetros é igual {cent} e em kilometros {kilo}')

"""Exercício 10"""

a = int(input('Escolha um número = '))
b = int(input('Escolha um número = '))
c = int(input('Escolha um número = '))

if a < b and b < c:
    print('A é o menor')
    print('C é o maior')
elif a < c and c < b:
    print('A é o menor')
    print('B é o maior')
elif c < b and b < a:
    print('C é o menor')
    print('A é o maior')
elif c < a and a < b:
    print('C é o menor')
    print('B é o maior')
elif b < c and c < a:
    print('B é o menor')
    print('C é o maior')
elif b < a and a < c:
    print('B é o menor')
    print('C é o maior')

"""Exercício 11"""

a = int(input('Escolha um número = '))
b = int(input('Escolha um número = '))
c = int(input('Escolha um número = '))

if a < b and b < c:
    print(f'{c}, {b}, {a}')
elif a < c and c < b:
    print(f'{b}, {c}, {a}')
elif c < b and b < a:
    print(f'{a}, {b}, {c}')
elif c < a and a < b:
    print(f'{b}, {a}, {c}')
elif b < c and c < a:
    print(f'{a}, {c}, {b}')
elif b < a and a < c:
    print(f'{c}, {a}, {b}')

"""Exercício 12"""

a = int(input('Escolha um número = '))
b = int(input('Escolha um número = '))
ind = input('Escolha um indicador = ')

if ind == "+":
    print (f'{a} + {b} = {a + b}')
elif ind == '-':
    print (f'{a} - {b} = {a - b}')
elif ind == 'x':
    print(f'{a} x {b} = {a*b}')
elif ind == '/':
    print(f'{a} / {b} = {a/b}')

"""Exercício 13"""

prova = float(input('Qual a sua nota = '))
trabalho = float(input('Qual a sua nota = '))
atividade = float(input('Qual a sua nota = '))
part = float(input('Qual a sua nota = '))

media = (prova*4 + trabalho*3 + atividade*2 + part) / 10

if media >= 7:
    print(media)
    print('APROVADO')
elif media >= 5:
    print(media)
    print('Reprovado')
elif media < 5:
    print(media)
    print('exame')

"""Exercício 14

"""

a = int(input('Escolha um número = '))
if a == 0:
    print('A equação NÃO é do 2º grau, ENCERRADO')
b = int(input('Escolha um número = '))
c = int(input('Escolha um número = '))

delta = b**2 - 4*a*c
if delta < 0:
    print(f' Delta igual a {delta}, a equação não possui raizes reais pois o DELTA é NEGATIVO, programa ENCERRADO')
elif delta == 0:    
    x = (-(b) + delta**(1/2))/(2*a)
    print(f'Delta é igual {delta}, raiz é igual a {x} ')
elif delta > 0:
    x1 = (-(b) + delta**(1/2))/(2*a)
    x2 = (-(b) - delta**(1/2))/(2*a)
    print(f'x1 é igual {delta}, raiz 1 é igual a {x1} ')
    print(f'x2 é igual {delta}, raiz 2 é igual a {x2} ')

"""Exercício 15"""

salario = float(input('Qual o valor do salário do funcionário? '))

por = 0.2

if salario <= 800:
    aumento = salario + (salario*por)
elif salario <= 1300:
    por = por - 0.5
    aumento = salario + (salario*por)
elif salario <= 2500:
    por = por - 0.1
    aumento = salario + (salario*por)
elif salario > 2500:
    por = por - 0.15
    aumento = salario + (salario*por)

print(f'Salário antes do aumento é igual a R${salario:.2f}')
print(f'O percentual de aumento foi de {por*100} %')
print(f'O valor do aumento foi de R$ {aumento - salario:.2f}')
print(f'O novo salario é de R$ {aumento:.2F}')

"""Exercício 15a

"""

salario = float(input('Qual o valor do salário do funcionário? '))

por = 0.2

if salario <= 800:
    por = 0.2
    aumento = salario*por
elif salario <= 1300:
    por = por - 0.5
    aumento = salario*por
elif salario <= 2500:
    por = por - 0.1
    aumento = salario*por
elif salario > 2500:
    por = por - 0.15
    aumento = salario*por

print(f'Salário antes do aumento é igual a R${salario:.2f}')
print(f'O percentual de aumento foi de {por*100} %')
print(f'O valor do aumento foi de R$ {aumento:.2f}')
print(f'O novo salario é de R$ {aumento + salario:.2F}')

"""Exercício 16"""

numero = int(input('Digite um numero inteiro positivo: '))

unidade = numero % 10

numero = (numero - unidade)/10
dezena = numero % 10

numero = (numero - dezena)/10
centena = numero

dezena = int(dezena)
centena = int(centena)

if centena > 1:´
    c = 'centenas'
else:
    c = 'centena'

if dezena > 1:
    d = 'dezenas'
else:
    d = 'dezena'

if unidade > 1:
    u = 'unidades'
else:
    u = 'unidade'

if numero >= 100:
    print(f'{centena} {c}, {dezena} {d} e {unidade} {u}')
elif numero >= 10:
    print(f'{dezena} {d} e {unidade} {u}')
elif numero < 10:
    print(f'{unidade} {u}')

"""Exercício 16a"""

numero = int(input('Digite um numero inteiro positivo: '))

centena = int(numero/100)
numero = numero - (centena*100)

dezena = int(numero/10)
numero = numero - (dezena*10)

unidade = numero

if centena > 1:
    c = 'centenas'
else:
    c = 'centena'

if dezena > 1:
    d = 'dezenas'
else:
    d = 'dezena'

if unidade > 1:
    u = 'unidades'
else:
    u = 'unidade'

print(f'{centena} {c}, {dezena} {d} e {unidade} {u}')

"""Exercício 17"""

saque = int(input('Qual o valor a sacar = '))

div = saque

if saque < 10 or saque > 600:
    print('Saque impossível valor não permitido')

nota100 = int(saque/100)
saque = saque - (nota100*100)

nota50 = int(saque/50)
saque = saque - (nota50*50)

nota10 = int(saque/10)
saque = saque - (nota10*10)

nota5 = int(saque/5)
saque = saque - (nota5*5)

nota1 = saque

if nota100 > 1:
    a = 'notas'
else:
    a = 'nota'

if nota50 > 1:
    b = 'notas'
else:
    b = 'nota'

if nota10 > 1:
    c = 'notas'
else:
    c = 'nota'
if nota5 > 1:
    d = 'notas'
else:
    d = 'nota'

if nota1 > 1:
    e = 'notas'
else:
    e = 'nota'

div = str(div)
mensagem = 'Para sacar a quantia de' + ' ' + div + ' ' + 'reais, o programa fornece' + ' '

if nota100 > 0:
    nota100 = str(nota100)
    mensagem = mensagem + nota100 + ' ' + a + ' ' +'de 100 reais,' + ' '
else:
    mensagem = mensagem + ''

if nota50 > 0:
    nota50 = str(nota50)
    mensagem = mensagem + nota50 + ' ' + b + ' ' + 'de 50 reais,' + ' '
else:
    mensagem = mensagem + ''

if nota10 > 0:
    nota10 = str(nota10)
    mensagem = mensagem + nota10 + ' ' + c + ' ' +'de 10 reais,' + ' '
else:
    mensagem = mensagem + ''

if nota5 > 0:
    nota5 = str(nota5)
    mensagem = mensagem + nota5 + ' ' + d + ' ' + 'de 5 reais,'
else:
    mensagem = mensagem + ''

if nota1 > 0:
    nota1 = str(nota1)
    mensagem = mensagem + ' ' + nota1 + ' ' + e + ' ' +'de 1 real'
else:
    mensagem = mensagem + ''
    
print(mensagem)

"""Exercício 17a"""

saque = int(input('Qual o valor do saque = '))

if saque < 10 or saque > 600:
    print('Saque impossível valor não permitido')

nota100 = saque//100
nota50 = (saque%100)//50
nota10 = ((saque%100)%50)//10
nota5 = (((saque%100)%50)%10)//5
nota1 = (((saque%100)%50)%10)%5

if nota100 > 1:
    a = 'notas'
else:
    a = 'nota'

if nota50 > 1:
    b = 'notas'
else:
    b = 'nota'

if nota10 > 1:
    c = 'notas'
else:
    c = 'nota'
if nota5 > 1:
    d = 'notas'
else:
    d = 'nota'

if nota1 > 1:
    e = 'notas'
else:
    e = 'nota'

print(f'Para sacar a quantia de {saque} reais, o programa fornece {nota100} {a} de 100, {nota50} {b} de 50, {nota10} {c} de 10, {nota5} {d} de 5 e {nota1} {e} de 1')

"""Exercício 17b

"""

saque = int(input('Qual o valor a sacar = '))

if saque < 10 or saque > 600:
    print('Saque impossível valor não permitido')

nota100 = int(saque/100)
saque = saque - (nota100*100)

nota50 = int(saque/50)
saque = saque - (nota50*50)

nota10 = int(saque/10)
saque = saque - (nota10*10)

nota5 = int(saque/5)
saque = saque - (nota5*5)

nota1 = saque

if nota100 > 1:
    a = 'Notas'
else:
    a = 'Nota'

if nota50 > 1:
    b = 'Notas'
else:
    b = 'Nota'

if nota10 > 1:
    c = 'Notas'
else:
    c = 'Nota'
if nota5 > 1:
    d = 'Notas'
else:
    d = 'Nota'

if nota1 > 1:
    e = 'Notas'
else:
    e = 'Nota'
    
if nota100 > 0:
    print(f'{a} R$100,00 = {nota100}')
if nota50 > 0:
    print(f'{b} R$ 50,00 = {nota50}')
if nota10 > 0:
    print(f'{c} R$ 10,00 = {nota10}')
if nota5 > 0:
    print(f'{d} R$  5,00 = {nota5}')
if nota1 > 0:
    print(f'{e} R$  1,00 = {nota1}')

"""Exercício 18"""

n = int(input('Escolha um número = '))

if n%2 == 0:
    print('PAR')
else:
    print('IMPAR')

"""Exercício 19"""

morango = float(input('Quantos kilos de morango comprou? '))
maca = float(input('Quantos kilos de maçã comprou? '))

peso = morango + maca

vlmo = morango * 2.50
if morango > 5:
    vlmo = morango * 2.20
vlma = maca * 1.80
if maca > 5:
    vlma = maca * 1.50

total = vlma + vlmo

if peso > 8 or total > 25.00:
    total = total - (total * 0.1)

print(f'O total a ser pago será de {total:.2f}')

"""Exercício 20"""

n = int(input('Escolha um ano para ver se ele é bissexto = '))

if (n%4 == 0 and n%100 != 0) or n%400 == 0:
    print('Ano Bissexto')
else:
    print('NÃO bissexto')